sonar.projectKey=amurlaniakea_ai-guard-gateway
sonar.organization=amurlaniakea
sonar.sources=.
sonar.python.version=3.12
sonar.exclusions=tests/**
sonar.sourceEncoding=UTF-8

sonar.issue.ignore.multicriteria=b1
sonar.issue.ignore.multicriteria.b1.ruleKey=python:S1559
sonar.issue.ignore.multicriteria.b1.resourceKey=**/tests/**