sonar.projectKey=amurlaniakea_ai-guard-gateway
sonar.organization=amurlaniakea
sonar.sources=.
sonar.python.version=3.12
sonar.exclusions=tests/**,coverage.xml
sonar.python.coverage.reportPaths=coverage.xml

# Ignorar el bind 0.0.0.0 (S5122) en main.py
sonar.issue.ignore.multicriteria=b1,b2
sonar.issue.ignore.multicriteria.b1.ruleKey=python:S1559
sonar.issue.ignore.multicriteria.b1.resourceKey=**/tests/**
sonar.issue.ignore.multicriteria.b2.ruleKey=python:S5122
sonar.issue.ignore.multicriteria.b2.resourceKey=main.py

sonar.sourceEncoding=UTF-8